/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * IUCobrarFacturaPaciente.java
 *
 * Created on Nov 18, 2011, 7:12:59 PM
 */
package cobrar_factura_paciente;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import util.ServiciosTiempo;

/**
 *
 * @author Gabriel
 */
public class IUCobrarFacturaPaciente extends javax.swing.JFrame {
   private DefaultTableModel tablaFacturas;
   private ControladorCobrarFacturaPaciente controlador;

   /** Creates new form IUCobrarFacturaPaciente */
   public IUCobrarFacturaPaciente() {
      // crea la tabla personalizada
      tablaFacturas = new DefaultTableModel();
      initComponents();
      // guarda la referencia al controlador
      controlador = new ControladorCobrarFacturaPaciente();
      // arma la tabla
      armarTablaFacturas();
      // carga la tabla
      cargarFacturas();
   } // fin del constructor

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneTablaFacturas = new javax.swing.JScrollPane();
        tablaFacturasExterna = new javax.swing.JTable();
        botonCobrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Facturas a Cobrar");

        tablaFacturasExterna.setModel(tablaFacturas);
        scrollPaneTablaFacturas.setViewportView(tablaFacturasExterna);

        botonCobrar.setText("Cobrar");
        botonCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCobrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneTablaFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneTablaFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void botonCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCobrarActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_botonCobrarActionPerformed
   // fin del método botonCobrarActionPerformed
   
   private void armarTablaFacturas(){
      // configura la cabecera de las columnas
      tablaFacturas.addColumn("Nº Factura");
      tablaFacturas.addColumn("Fecha");
      tablaFacturas.addColumn("Nº Ficha");
      tablaFacturas.addColumn("Paciente");
      tablaFacturas.addColumn("Prestación");
      tablaFacturas.addColumn("Monto");
      
      // configura el ancho de las columnas
      tablaFacturasExterna.getColumnModel().getColumn(0).setMinWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(0).setMaxWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(1).setMinWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(1).setMaxWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(2).setMinWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(2).setMaxWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(3).setMinWidth(150);
      tablaFacturasExterna.getColumnModel().getColumn(3).setMaxWidth(150);
      tablaFacturasExterna.getColumnModel().getColumn(4).setMinWidth(150);
      tablaFacturasExterna.getColumnModel().getColumn(4).setMaxWidth(150);
      tablaFacturasExterna.getColumnModel().getColumn(5).setMinWidth(75);
      tablaFacturasExterna.getColumnModel().getColumn(5).setMaxWidth(75);
   } // fin del método armarTablaFacturas
   
   private void cargarFacturas(){
      List<DTOFacturaPaciente> listaFacturas = controlador.buscarFacturasPacientes();
      int fila = 0, col;
      
      tablaFacturas.setRowCount(listaFacturas.size());
      
      for(DTOFacturaPaciente dtoFactura : listaFacturas){
         col = 0;
         tablaFacturas.setValueAt(dtoFactura.getNumFactura(), fila, col++);
         tablaFacturas.setValueAt(ServiciosTiempo.dateToStringDDMMAAAA(dtoFactura.getFecha()), fila, col++);
         tablaFacturas.setValueAt(dtoFactura.getNroFicha(), fila, col++);
         tablaFacturas.setValueAt(dtoFactura.getNombrePaciente(), fila, col++);
         tablaFacturas.setValueAt(dtoFactura.getNombrePrestacion(), fila, col++);
         tablaFacturas.setValueAt(dtoFactura.getMonto(), fila, col++);
         fila++;
      } // fin de for de llenado de la tabla de facturas
   } // fin del método cargarFacturas
   
   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
       * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(IUCobrarFacturaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(IUCobrarFacturaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(IUCobrarFacturaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(IUCobrarFacturaPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {

         public void run() {
            new IUCobrarFacturaPaciente().setVisible(true);
         }
      });
   } // fin del método main
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCobrar;
    private javax.swing.JScrollPane scrollPaneTablaFacturas;
    private javax.swing.JTable tablaFacturasExterna;
    // End of variables declaration//GEN-END:variables
} // fin de la clase IUCobrarFacturaPaciente