package generar_factura_paciente;

import dtos.DTODetalleServicio;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import dtos.DTOFichaInternacion;
import javax.swing.JOptionPane;
import util.ServiciosTiempo;

public class IUGenerarFacturaPaciente extends javax.swing.JFrame {
   private DefaultTableModel tablaFichas;
   private ControladorGenerarFacturaPaciente controlador;
   
   public IUGenerarFacturaPaciente() {
      this.tablaFichas = new DefaultTableModel();
      initComponents();
      this.setLocationRelativeTo(null);
      armarTabla();
   } // fin del constructor

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
   */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      etiqueteNumFicha = new javax.swing.JLabel();
      botonBuscarFicha = new javax.swing.JButton();
      botonGenerarFactura = new javax.swing.JButton();
      campoTextoNumFicha = new javax.swing.JTextField();
      botonMostrarFIcha = new javax.swing.JButton();
      panelDatosFicha = new javax.swing.JPanel();
      etiquetaNumPaciente = new javax.swing.JLabel();
      etiquetaNombrePaciente = new javax.swing.JLabel();
      etiquetaNombrePrestacion = new javax.swing.JLabel();
      etiquetaCostoPrestacion = new javax.swing.JLabel();
      etiquetaCoseguro = new javax.swing.JLabel();
      etiquetaFecha = new javax.swing.JLabel();
      campoTextoFecha = new javax.swing.JTextField();
      campoTextoNumPaciente = new javax.swing.JTextField();
      campoTextoNombrePaciente = new javax.swing.JTextField();
      campoTextoNombrePrestacion = new javax.swing.JTextField();
      campoTextoCostoPrestacion = new javax.swing.JTextField();
      campoTextoCoseguro = new javax.swing.JTextField();
      scrollPaneServiciosEspeciales = new javax.swing.JScrollPane();
      tablaFichasExterna = new javax.swing.JTable();
      botonVolver = new javax.swing.JButton();

      etiqueteNumFicha.setText("Nº Ficha Internacion:");

      botonBuscarFicha.setText("Buscar Ficha");

      botonGenerarFactura.setText("Generar Factura");
      botonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonGenerarFacturaActionPerformed(evt);
         }
      });

      botonMostrarFIcha.setText("Mostrar Ficha");
      botonMostrarFIcha.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonMostrarFIchaActionPerformed(evt);
         }
      });

      panelDatosFicha.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Ficha"));

      etiquetaNumPaciente.setText("Nº Paciente:");

      etiquetaNombrePaciente.setText("Nombre Paciente:");

      etiquetaNombrePrestacion.setText("Prestación:");

      etiquetaCostoPrestacion.setText("Costo Prestación:");

      etiquetaCoseguro.setText("Coseguro:");

      etiquetaFecha.setText("Fecha:");

      javax.swing.GroupLayout panelDatosFichaLayout = new javax.swing.GroupLayout(panelDatosFicha);
      panelDatosFicha.setLayout(panelDatosFichaLayout);
      panelDatosFichaLayout.setHorizontalGroup(
         panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelDatosFichaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(etiquetaFecha)
               .addComponent(etiquetaCoseguro)
               .addComponent(etiquetaCostoPrestacion)
               .addComponent(etiquetaNombrePrestacion)
               .addComponent(etiquetaNumPaciente)
               .addComponent(etiquetaNombrePaciente))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
               .addComponent(campoTextoCoseguro)
               .addComponent(campoTextoCostoPrestacion)
               .addComponent(campoTextoNombrePrestacion)
               .addComponent(campoTextoNombrePaciente)
               .addComponent(campoTextoNumPaciente)
               .addComponent(campoTextoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
            .addContainerGap(330, Short.MAX_VALUE))
      );
      panelDatosFichaLayout.setVerticalGroup(
         panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(panelDatosFichaLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiquetaFecha)
               .addComponent(campoTextoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiquetaNumPaciente)
               .addComponent(campoTextoNumPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiquetaNombrePaciente)
               .addComponent(campoTextoNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiquetaNombrePrestacion)
               .addComponent(campoTextoNombrePrestacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiquetaCostoPrestacion)
               .addComponent(campoTextoCostoPrestacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiquetaCoseguro)
               .addComponent(campoTextoCoseguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      scrollPaneServiciosEspeciales.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios Especiales"));

      tablaFichasExterna.setModel(tablaFichas);
      scrollPaneServiciosEspeciales.setViewportView(tablaFichasExterna);

      botonVolver.setText("Volver");
      botonVolver.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            botonVolverActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addComponent(etiqueteNumFicha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(botonMostrarFIcha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(campoTextoNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(botonBuscarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                     .addComponent(panelDatosFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                  .addGap(62, 62, 62)
                  .addComponent(botonVolver)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 516, Short.MAX_VALUE)
                  .addComponent(botonGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(8, 8, 8))
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(scrollPaneServiciosEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(etiqueteNumFicha)
               .addComponent(campoTextoNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(botonBuscarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(botonMostrarFIcha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(panelDatosFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(scrollPaneServiciosEspeciales, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
            .addGap(58, 58, 58)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(botonGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(botonVolver))
            .addGap(24, 24, 24))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void botonMostrarFIchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarFIchaActionPerformed
      cargarCampos();
   }//GEN-LAST:event_botonMostrarFIchaActionPerformed
   // fin del método botonMostrarFIchaActionPerformed
   
   private void botonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarFacturaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_botonGenerarFacturaActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_botonVolverActionPerformed
   // fin del método botonGenerarFacturaActionPerformed
   
   private void armarTabla(){
      // crea las columnas de la tabla
      this.tablaFichas.addColumn("Servicio");
      this.tablaFichas.addColumn("Cantidad");
      this.tablaFichas.addColumn("Costo");
      this.tablaFichas.addColumn("Subtotal");
      
      // configura el ancho de las columnas
      this.tablaFichasExterna.getColumnModel().getColumn(0).setMinWidth(75);
      this.tablaFichasExterna.getColumnModel().getColumn(0).setMaxWidth(75);
   } // fin del método armarTabla
   
   private void cargarCampos(){
      try{
         int numFicha = Integer.parseInt(this.campoTextoNumFicha.getText());
         DTOFichaInternacion fichaInt = this.controlador.buscarFicha(numFicha);
         int fila = 0, col;
         
         this.campoTextoFecha.setText(ServiciosTiempo.dateToStringDDMMAAAA(fichaInt.getFecha()));
         this.campoTextoNumPaciente.setText(fichaInt.getNumPaciente() + "");
         this.campoTextoNombrePaciente.setText(fichaInt.getNombrePaciente());
         this.campoTextoNombrePrestacion.setText(fichaInt.getNombrePrestacion());
         this.campoTextoCostoPrestacion.setText(fichaInt.getCostoPrestacion() + "");
         this.campoTextoCoseguro.setText(fichaInt.getDescuento() + "");
         
         List<DTODetalleServicio> listaDetalle = fichaInt.getDtoDetalle();
         
         for(DTODetalleServicio dtoDetalle : listaDetalle){
            col = 0;
            this.tablaFichas.setValueAt(dtoDetalle.getNombreServicio(), fila, col++);
            this.tablaFichas.setValueAt(dtoDetalle.getCantidad(), fila, col++);
            this.tablaFichas.setValueAt(dtoDetalle.getMonto(), fila, col++);
            this.tablaFichas.setValueAt(dtoDetalle.getSubtotal(), fila, col++);
         } // fin de for de llenado de la tabla de detalles de servicios especiales
      } // fin de try de error de formato
      catch(NumberFormatException ex){
         JOptionPane.showMessageDialog(null, "Debe ingresar un número en el campo \"Nº Ficha Internacion:\"");
      } // fin de catch de error de formato
   } // fin del método cargarCampos
   
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton botonBuscarFicha;
   private javax.swing.JButton botonGenerarFactura;
   private javax.swing.JButton botonMostrarFIcha;
   private javax.swing.JButton botonVolver;
   private javax.swing.JTextField campoTextoCoseguro;
   private javax.swing.JTextField campoTextoCostoPrestacion;
   private javax.swing.JTextField campoTextoFecha;
   private javax.swing.JTextField campoTextoNombrePaciente;
   private javax.swing.JTextField campoTextoNombrePrestacion;
   private javax.swing.JTextField campoTextoNumFicha;
   private javax.swing.JTextField campoTextoNumPaciente;
   private javax.swing.JLabel etiquetaCoseguro;
   private javax.swing.JLabel etiquetaCostoPrestacion;
   private javax.swing.JLabel etiquetaFecha;
   private javax.swing.JLabel etiquetaNombrePaciente;
   private javax.swing.JLabel etiquetaNombrePrestacion;
   private javax.swing.JLabel etiquetaNumPaciente;
   private javax.swing.JLabel etiqueteNumFicha;
   private javax.swing.JPanel panelDatosFicha;
   private javax.swing.JScrollPane scrollPaneServiciosEspeciales;
   private javax.swing.JTable tablaFichasExterna;
   // End of variables declaration//GEN-END:variables
} // fin de la clase IUGenerarFacturaPaciente