package generar_factura_paciente;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import dtos.DTOFichaInternacion;

public class IUGenerarFacturaPaciente extends javax.swing.JFrame {
   private DefaultTableModel tablaFechas;
   private ControladorGenerarFacturaPaciente controlador;
   
   public IUGenerarFacturaPaciente() {
      this.tablaFechas = new DefaultTableModel();
      initComponents();
   } // fin del constructor

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
   */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueteNumFicha = new javax.swing.JLabel();
        botonBuscarFicha = new javax.swing.JButton();
        etiquetaTotal = new javax.swing.JLabel();
        campoTextoTotal = new javax.swing.JTextField();
        botonGenerarFactura = new javax.swing.JButton();
        campoTextoNumFicha = new javax.swing.JTextField();
        botonMostrarFIcha = new javax.swing.JButton();
        panelDatosFicha = new javax.swing.JPanel();
        etiquetaNumPaciente = new javax.swing.JLabel();
        etiquetaNombrePaciente = new javax.swing.JLabel();
        etiquetaNombrePrestacion = new javax.swing.JLabel();
        etiquetaCostoPrestacion = new javax.swing.JLabel();
        etiquetaCoseguro = new javax.swing.JLabel();
        etiquetaFecha = new javax.swing.JLabel();
        campoTextoFecha = new javax.swing.JTextField();
        campoTextoNumPaciente = new javax.swing.JTextField();
        campoTextoNombrePeciente = new javax.swing.JTextField();
        campoTextoNombrePrestacion = new javax.swing.JTextField();
        campoTextoCostoPrestacion = new javax.swing.JTextField();
        campoTextoCoseguro = new javax.swing.JTextField();
        scrollPaneServiciosEspeciales = new javax.swing.JScrollPane();
        tablaFichasExterna = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etiqueteNumFicha.setText("Nº Ficha Internacion:");

        botonBuscarFicha.setText("Buscar Ficha");

        etiquetaTotal.setFont(new java.awt.Font("Tahoma", 1, 14));
        etiquetaTotal.setText("IMPORTE TOTAL:");

        campoTextoTotal.setEditable(false);

        botonGenerarFactura.setText("Generar Factura");
        botonGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGenerarFacturaActionPerformed(evt);
            }
        });

        botonMostrarFIcha.setText("Mostrar Ficha");
        botonMostrarFIcha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarFIchaActionPerformed(evt);
            }
        });

        panelDatosFicha.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Ficha"));

        etiquetaNumPaciente.setText("Nº Paciente:");

        etiquetaNombrePaciente.setText("Nombre Paciente:");

        etiquetaNombrePrestacion.setText("Prestación:");

        etiquetaCostoPrestacion.setText("Costo Prestación:");

        etiquetaCoseguro.setText("Coseguro:");

        etiquetaFecha.setText("Fecha:");

        javax.swing.GroupLayout panelDatosFichaLayout = new javax.swing.GroupLayout(panelDatosFicha);
        panelDatosFicha.setLayout(panelDatosFichaLayout);
        panelDatosFichaLayout.setHorizontalGroup(
            panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaFecha)
                    .addComponent(etiquetaCoseguro)
                    .addComponent(etiquetaCostoPrestacion)
                    .addComponent(etiquetaNombrePrestacion)
                    .addComponent(etiquetaNumPaciente)
                    .addComponent(etiquetaNombrePaciente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoTextoCoseguro)
                    .addComponent(campoTextoCostoPrestacion)
                    .addComponent(campoTextoNombrePrestacion)
                    .addComponent(campoTextoNombrePeciente)
                    .addComponent(campoTextoNumPaciente)
                    .addComponent(campoTextoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelDatosFichaLayout.setVerticalGroup(
            panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosFichaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaFecha)
                    .addComponent(campoTextoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNumPaciente)
                    .addComponent(campoTextoNumPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombrePaciente)
                    .addComponent(campoTextoNombrePeciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaNombrePrestacion)
                    .addComponent(campoTextoNombrePrestacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCostoPrestacion)
                    .addComponent(campoTextoCostoPrestacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDatosFichaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaCoseguro)
                    .addComponent(campoTextoCoseguro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPaneServiciosEspeciales.setBorder(javax.swing.BorderFactory.createTitledBorder("Servicios Especiales"));

        tablaFichasExterna.setModel(tablaFechas);
        scrollPaneServiciosEspeciales.setViewportView(tablaFichasExterna);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(etiqueteNumFicha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMostrarFIcha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoTextoNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonBuscarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelDatosFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(479, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(etiquetaTotal)
                        .addGap(32, 32, 32)
                        .addComponent(campoTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(botonGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneServiciosEspeciales, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqueteNumFicha)
                    .addComponent(campoTextoNumFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBuscarFicha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonMostrarFIcha, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDatosFicha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneServiciosEspeciales, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTextoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaTotal))
                .addGap(18, 18, 18)
                .addComponent(botonGenerarFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void botonMostrarFIchaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarFIchaActionPerformed
      cargarCampos();
   }//GEN-LAST:event_botonMostrarFIchaActionPerformed
   // fin del método botonMostrarFIchaActionPerformed
   
   private void botonGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGenerarFacturaActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_botonGenerarFacturaActionPerformed
   // fin del método botonGenerarFacturaActionPerformed
   
   private void cargarCampos(){
      
   } // fin del método cargarCampos
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscarFicha;
    private javax.swing.JButton botonGenerarFactura;
    private javax.swing.JButton botonMostrarFIcha;
    private javax.swing.JTextField campoTextoCoseguro;
    private javax.swing.JTextField campoTextoCostoPrestacion;
    private javax.swing.JTextField campoTextoFecha;
    private javax.swing.JTextField campoTextoNombrePeciente;
    private javax.swing.JTextField campoTextoNombrePrestacion;
    private javax.swing.JTextField campoTextoNumFicha;
    private javax.swing.JTextField campoTextoNumPaciente;
    private javax.swing.JTextField campoTextoTotal;
    private javax.swing.JLabel etiquetaCoseguro;
    private javax.swing.JLabel etiquetaCostoPrestacion;
    private javax.swing.JLabel etiquetaFecha;
    private javax.swing.JLabel etiquetaNombrePaciente;
    private javax.swing.JLabel etiquetaNombrePrestacion;
    private javax.swing.JLabel etiquetaNumPaciente;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JLabel etiqueteNumFicha;
    private javax.swing.JPanel panelDatosFicha;
    private javax.swing.JScrollPane scrollPaneServiciosEspeciales;
    private javax.swing.JTable tablaFichasExterna;
    // End of variables declaration//GEN-END:variables
} // fin de la clase IUGenerarFacturaPaciente