package generar_factura_paciente;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import dtos.DTOFichaInternacion;

public class IUMostrarFichasPendientes extends javax.swing.JFrame {
   private DefaultTableModel tablaFichasPendientes;
   private ControladorGenerarFacturaPaciente controlador;
   
   public IUMostrarFichasPendientes(ControladorGenerarFacturaPaciente controlador) {
      // crea la tabla para las fichas pendientes de facturación
      this.tablaFichasPendientes = new DefaultTableModel();
      // inicializa los componentes de la GUI
      initComponents();
      // centra la GUI en la pantalla
      this.setLocationRelativeTo(null);
      // guarda el controlador con el que se comunicará la GUI
      this.controlador = controlador;
      // arma la cabecera de la tabla
      armarTabla();
   } // fin del constructor

   /** This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPaneFichasPendientes = new javax.swing.JScrollPane();
        tablaFichasPendientesExterna = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fichas Pendientes de Facturación");

        tablaFichasPendientesExterna.setModel(tablaFichasPendientes);
        tablaFichasPendientesExterna.setEnabled(false);
        tablaFichasPendientesExterna.setFocusable(false);
        tablaFichasPendientesExterna.setRequestFocusEnabled(false);
        tablaFichasPendientesExterna.setRowSelectionAllowed(false);
        tablaFichasPendientesExterna.setVerifyInputWhenFocusTarget(false);
        scrollPaneFichasPendientes.setViewportView(tablaFichasPendientesExterna);

        botonVolver.setText("Volver");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });

        botonAceptar.setText("Aceptar");
        botonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPaneFichasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneFichasPendientes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonVolver)
                    .addComponent(botonAceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void botonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAceptarActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_botonAceptarActionPerformed
   // fin del método botonAceptarActionPerformed
   
   private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
      this.setVisible(false);
   }//GEN-LAST:event_botonVolverActionPerformed
   // fin del método botonVolverActionPerformed
   
   private void armarTabla(){
      this.tablaFichasPendientes.addColumn("Nº Ficha");
      this.tablaFichasPendientes.addColumn("Fecha");
      this.tablaFichasPendientes.addColumn("Paciente");
      this.tablaFichasPendientes.addColumn("Prestación");
   } // fin del método armarTabla
   
   public void cargarTabla(List<DTOFichaInternacion> listaDtoFichas){
      
   } // fin del método cargarTabla
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JScrollPane scrollPaneFichasPendientes;
    private javax.swing.JTable tablaFichasPendientesExterna;
    // End of variables declaration//GEN-END:variables
} // fin de la clase IUMostrarFichasPendientes